const disclaimer = 'Independent study aid. RolePrep is not affiliated with or endorsed by CompTIA. Exam policies and objectives can change; verify the current official CompTIA exam objectives before booking.'

const concept = (term, definition, example, contrast) => ({ term, definition, example, contrast })
const domain = (title, summary, concepts) => ({ title, summary, concepts })

function buildTrack(config) {
  const modules = config.domains.map((item, index) => ({
    id: `${config.id}-${index + 1}`,
    number: String(index + 1).padStart(2, '0'),
    title: item.title,
    time: item.time || '75–90 min',
    activityLabel: 'CERTIFICATION PRACTICE',
    summary: item.summary,
    objectives: [
      `Explain the essential vocabulary in ${item.title.toLowerCase()}`,
      `Apply ${item.title.toLowerCase()} concepts to a practical scenario`,
      'Eliminate tempting exam distractors by explaining the underlying distinction'
    ],
    sections: item.concepts.map((entry, conceptIndex) => ({
      title: entry.term,
      paragraphs: [
        `${entry.definition} This matters because certification questions rarely test a term in isolation: they describe a goal, symptom, risk, or constraint and ask you to choose the concept or action that best fits. Start by restating the definition in your own words, then identify the clue that separates it from related ideas.`,
        `For example, ${entry.example} A common mistake is to confuse this with ${entry.contrast}. On the exam and in real work, read the entire scenario, identify what outcome is needed, choose the least risky effective action, and verify the result rather than matching on one familiar word.`
      ],
      terms: [[entry.term, entry.definition]],
      checkpoint: {
        question: `How would you recognize ${entry.term} in a scenario?`,
        answer: `Look for a situation where ${entry.example} The defining idea is: ${entry.definition}`
      },
      steps: conceptIndex === item.concepts.length - 1 ? ['Identify the desired outcome.', 'Note the evidence and constraints.', 'Name the relevant concept.', 'Choose the safest effective action.', 'Validate and document the result.'] : undefined
    })),
    command: `Teach-back drill: define ${item.concepts.map(entry => entry.term).join(', ')} without notes.`,
    commandNote: `Then create one new scenario for each term and explain why the other concepts in this module would be weaker answers.`,
    interviewQuestions: item.concepts.slice(0, 3).map(entry => ({ question: `Explain ${entry.term} and give a practical example.`, example: `${entry.definition} A practical example is when ${entry.example}` }))
  }))

  const allConcepts = config.domains.flatMap(item => item.concepts)
  const definitionQuestions = allConcepts.map((entry, index) => {
    const distractors = [1, 5, 11].map(offset => allConcepts[(index + offset) % allConcepts.length].definition)
    return { q: `Which statement best describes ${entry.term}?`, choices: [entry.definition, ...distractors], answer: 0, why: `${entry.term}: ${entry.definition}` }
  })
  const scenarioQuestions = config.domains.map((item, index) => {
    const answer = item.concepts[index % item.concepts.length]
    return { q: `Which concept best fits this situation: ${answer.example}`, choices: [answer.term, ...item.concepts.filter(entry => entry.term !== answer.term).slice(0, 3).map(entry => entry.term)], answer: 0, why: `${answer.term} is the closest match because ${answer.definition.toLowerCase()}` }
  })

  return {
    id: config.id,
    type: 'certification',
    category: `CERTIFICATION PREP · ${config.family}`,
    title: config.title,
    subtitle: config.subtitle,
    level: config.level,
    duration: config.duration,
    description: config.description,
    heroTitle: config.heroTitle,
    heroDescription: config.heroDescription,
    promptLabel: 'EXAM RECALL',
    promptInstruction: 'Answer without notes: define the concept, identify the scenario clue, choose the best action, and explain why a nearby concept is less suitable.',
    practiceEyebrow: `Apply ${config.shortTitle} skills to realistic exam scenarios`,
    practiceIntro: 'Work the problem before revealing the coaching notes. Performance-based questions reward correct sequencing, configuration judgment, troubleshooting, and validation—not vocabulary alone.',
    disclaimer,
    exam: { practiceMinutes: 50, scaled: true, ...config.exam },
    modules,
    quizQuestions: [...definitionQuestions, ...scenarioQuestions],
    glossary: allConcepts.map(entry => [entry.term, entry.definition]),
    scenarios: config.scenarios,
    featuredScenario: config.featuredScenario,
    console: config.console
  }
}

export const comptiaAPlusRole = buildTrack({
  id: 'comptia-a-plus-v15', family: 'COMPTIA CORE', title: 'CompTIA A+ (V15)', shortTitle: 'A+',
  subtitle: 'Core 1 220-1201 + Core 2 220-1202', level: 'Beginner', duration: '18–24 hours',
  description: 'Prepare for both current A+ exams through hardware, mobile devices, networking, virtualization, operating systems, security, troubleshooting, and professional operations.',
  heroTitle: 'Build a complete A+ foundation.', heroDescription: 'Learn how endpoint hardware, operating systems, networks, security, cloud services, and support workflows fit together. This track assumes you have never opened a computer or worked a help desk ticket.',
  exam: { version: 'V15 · 220-1201 & 220-1202', questions: 'Up to 90 each', minutes: 90, timeDisplay: '90 min each', passDisplay: '675 Core 1 · 700 Core 2', format: 'Multiple choice + performance-based' },
  domains: [
    domain('Mobile Devices', 'Identify, configure, connect, secure, and troubleshoot laptops, tablets, phones, and their accessories.', [
      concept('Laptop components', 'Field-replaceable laptop parts include memory, storage, batteries, keyboards, wireless cards, and displays, with model-specific service procedures.', 'a laptop with a swollen battery is powered down, isolated, and serviced using the manufacturer procedure.', 'treating every mobile component as interchangeable with desktop hardware'),
      concept('Mobile connectivity', 'Mobile devices use Wi-Fi, Bluetooth, NFC, cellular, USB, and tethering for different ranges, power needs, and purposes.', 'a headset pairs over Bluetooth while contactless payment uses NFC at very short range.', 'assuming every wireless technology provides internet access'),
      concept('Mobile synchronization', 'Synchronization keeps selected email, contacts, calendars, files, applications, and settings consistent across services and devices.', 'a user signs into an approved cloud account and chooses which work data can synchronize.', 'copying all data manually without considering ownership or security'),
      concept('Accessory troubleshooting', 'Mobile accessory faults are isolated by checking compatibility, power, ports, cables, pairing, permissions, drivers, and a known-good substitute.', 'a dock works with another laptop, narrowing the fault to the original device or its configuration.', 'replacing the dock before testing power and compatibility')
    ]),
    domain('Networking Fundamentals', 'Understand common network types, protocols, ports, addressing, wireless standards, and small-office equipment.', [
      concept('IP addressing', 'An IP address identifies an interface on a network; subnet information distinguishes local destinations from those reached through a gateway.', 'a client with a self-assigned 169.254 address is checked for DHCP reachability.', 'confusing an IP address with a device MAC address'),
      concept('DNS and DHCP', 'DNS translates names to addresses, while DHCP automatically supplies addressing settings such as IP, mask, gateway, and DNS servers.', 'a device reaches a server by IP but not hostname, so DNS is tested before DHCP.', 'treating name resolution and address assignment as the same service'),
      concept('Ports and protocols', 'Application protocols use well-known transport ports, such as HTTPS 443, SSH 22, DNS 53, and RDP 3389.', 'a firewall rule allows HTTPS to a web service without exposing unrelated ports.', 'assuming a port number alone proves traffic is safe'),
      concept('Wireless security', 'Modern wireless networks should use strong encryption, protected credentials, current firmware, and appropriate segmentation.', 'a business replaces legacy encryption with WPA3 or strong WPA2 settings and separates guest access.', 'hiding the SSID as the primary security control')
    ]),
    domain('PC Hardware', 'Recognize components, interfaces, power, storage, printers, and safe installation practices.', [
      concept('CPU and cooling', 'The CPU executes instructions and requires compatible sockets, firmware support, thermal interface material, and adequate cooling.', 'a system that shuts down under load is checked for fan operation, heatsink seating, dust, and temperature.', 'assuming every unexpected shutdown is an operating-system fault'),
      concept('Memory', 'RAM provides volatile working storage and must match supported type, speed, capacity, channel layout, and error-correction requirements.', 'memory errors are isolated by vendor diagnostics and testing supported modules one at a time.', 'confusing volatile RAM with persistent storage'),
      concept('Storage', 'HDDs, SATA SSDs, and NVMe SSDs differ in media, interfaces, performance, endurance, and installation requirements.', 'an NVMe drive is installed in a compatible M.2 slot using the supported key and protocol.', 'assuming every M.2 device uses NVMe'),
      concept('Power and electrical safety', 'Power work requires correct wattage, connectors, voltage awareness, ESD controls, safe discharge, and replacement rather than opening hazardous power supplies.', 'a technician disconnects power, uses ESD protection, and verifies PSU capacity before a GPU upgrade.', 'opening a power supply enclosure to repair energized high-voltage components')
    ]),
    domain('Virtualization, Cloud & IoT', 'Understand virtual machines, containers, cloud delivery models, shared resources, and connected devices.', [
      concept('Virtual machines', 'A hypervisor allocates host compute, memory, storage, and networking to isolated guest operating systems.', 'a technician snapshots a lab VM before a risky configuration exercise.', 'treating a snapshot as a complete long-term backup strategy'),
      concept('Cloud service models', 'IaaS, PaaS, and SaaS divide responsibility differently between provider and customer.', 'a company using webmail as SaaS still manages identities, access, and data handling.', 'assuming the cloud provider owns every security responsibility'),
      concept('Containers', 'Containers package applications and dependencies while sharing the host kernel, making them lighter than full virtual machines.', 'a development team runs isolated application containers from versioned images.', 'assuming a container includes a complete independent guest kernel'),
      concept('IoT devices', 'Connected devices require inventory, segmentation, supported firmware, credential changes, and lifecycle planning.', 'smart cameras are placed on a restricted network and default passwords are replaced.', 'connecting unmanaged devices directly to trusted production networks')
    ]),
    domain('Operating Systems', 'Install, configure, maintain, and troubleshoot Windows while recognizing macOS, Linux, mobile, and command-line tools.', [
      concept('Windows editions and requirements', 'Windows editions differ in features such as domain join, encryption, virtualization, and management; hardware must meet supported requirements.', 'a business selects an edition that supports centralized identity and device management.', 'choosing an edition only by its desktop appearance'),
      concept('File systems and permissions', 'File systems organize persistent data and enforce capabilities such as permissions, encryption, quotas, and journaling.', 'NTFS permissions are assigned to groups using least privilege rather than directly to many users.', 'assuming share permissions and local file permissions are identical'),
      concept('Command-line tools', 'Command-line tools expose repeatable diagnostics and administration for files, processes, disks, networking, and system configuration.', 'ipconfig, ping, nslookup, and netstat are selected according to the layer being tested.', 'running destructive commands before collecting read-only evidence'),
      concept('OS installation and recovery', 'A controlled installation includes compatibility, backups, partitions, drivers, updates, activation, security controls, applications, migration, and validation.', 'a failed update is approached through recovery options after user data and encryption keys are protected.', 'reimaging immediately without preserving data or identifying the failure')
    ]),
    domain('Security Fundamentals', 'Protect identities, devices, networks, data, and physical access with layered controls.', [
      concept('Authentication and MFA', 'Authentication verifies identity; multifactor authentication uses different factor types to reduce reliance on one credential.', 'a password plus an authenticator-generated code uses knowledge and possession factors.', 'calling two passwords multifactor authentication'),
      concept('Least privilege', 'Users and processes receive only the permissions needed for approved duties and no longer than necessary.', 'temporary administrative rights expire after an authorized software installation.', 'granting permanent local administrator access for convenience'),
      concept('Malware response', 'Malware handling prioritizes isolation, evidence, approved removal or reimage procedures, patching, credential protection, validation, and reporting.', 'an infected endpoint is disconnected from networks before approved response steps continue.', 'browsing for cleanup tools from the compromised computer'),
      concept('Data protection', 'Data protection combines classification, access control, encryption, backups, retention, secure disposal, and privacy requirements.', 'a retired encrypted drive is sanitized or destroyed according to policy and recorded.', 'deleting files and assuming the underlying data is unrecoverable')
    ]),
    domain('Software Troubleshooting', 'Use symptoms and evidence to diagnose operating-system, application, security, and mobile-device problems.', [
      concept('Troubleshooting methodology', 'A disciplined method identifies the problem, forms and tests a theory, plans and implements a solution, verifies full functionality, and documents findings.', 'one low-risk differentiating test is chosen instead of changing several settings.', 'guessing repeatedly without a baseline or rollback'),
      concept('Logs and symptoms', 'Logs, error messages, timelines, resource data, and reproduction steps are evidence that narrow hypotheses but do not automatically prove root cause.', 'a crash timestamp is correlated with application and system events plus a recent change.', 'replacing hardware because one warning event exists'),
      concept('User profiles and applications', 'Profile-specific faults are separated from device-wide faults by comparing users, clean profiles, permissions, and application state.', 'another user succeeds on the same PC, directing attention to the affected profile.', 'assuming a successful network test proves the user profile is healthy'),
      concept('Mobile security symptoms', 'Unexpected battery drain, heat, data usage, permissions, pop-ups, or configuration changes can indicate malicious or misbehaving software.', 'a managed phone is isolated and reported when suspicious management profiles appear.', 'factory-resetting before preserving required evidence and checking policy')
    ]),
    domain('Operational Procedures', 'Work safely, document clearly, manage changes and assets, communicate professionally, and protect the environment.', [
      concept('Ticket documentation', 'A useful ticket records symptom, scope, impact, evidence, tests, changes, approvals, validation, and follow-up without sensitive secrets.', 'another technician can continue the case from chronological notes.', 'closing with only the phrase fixed issue'),
      concept('Change management', 'Changes are assessed, authorized, scheduled, communicated, implemented with rollback, validated, and reviewed according to risk.', 'a broad software deployment is piloted before staged production rollout.', 'making an untracked global change during peak business hours'),
      concept('Asset lifecycle', 'Assets are requested, approved, purchased, tagged, assigned, maintained, inventoried, recovered, sanitized, and disposed with records.', 'a returned laptop is reconciled to inventory and securely prepared for reuse.', 'discarding equipment without updating ownership or sanitizing storage'),
      concept('Professional communication', 'Support communication uses empathy, plain language, active listening, realistic updates, appropriate escalation, and confirmation of the user outcome.', 'a technician states what is known, the next action, and the next update time without guessing.', 'blaming the user or hiding uncertainty behind jargon')
    ])
  ],
  scenarios: [
    { title: 'Laptop will not charge', prompt: 'A user reports that a laptop stopped charging after moving desks.', steps: ['Clarify the symptom and impact.', 'Inspect power source, adapter, port, battery, and indicators.', 'Use known-good compatible parts safely.', 'Separate charging failure from display or boot failure.', 'Document and validate.'], model: 'Begin with outlet and power-strip state, inspect the approved adapter and connector, check indicators and physical damage, perform a safe power reset if supported, test a known-good compatible adapter, and use vendor battery diagnostics. Isolate a swollen battery immediately and never improvise with incompatible power.' },
    { title: 'One site will not open', prompt: 'The computer reaches other websites, but one business application fails by name.', steps: ['Define scope.', 'Test name resolution.', 'Compare IP and name behavior.', 'Check proxy, time, certificate, and service health.', 'Avoid unrelated changes.'], model: 'Because general connectivity works, focus on DNS, application reachability, proxy or filtering, certificate and time, identity, and service health. Use nslookup and a controlled comparison, document evidence, and escalate with the exact error and scope.' },
    { title: 'Suspicious endpoint', prompt: 'A workstation displays unexpected pop-ups and makes unusual outbound connections.', steps: ['Protect people and systems.', 'Preserve evidence.', 'Follow incident policy.', 'Remediate and validate.', 'Prevent recurrence.'], model: 'Disconnect network access without powering off if policy favors live evidence, notify security, capture approved evidence, protect credentials, use approved quarantine or reimage procedures, patch the initial weakness, restore clean data, validate, and document.' },
    { title: 'Company-wide software rollout', prompt: 'A supervisor asks you to deploy a new client application to every workstation.', steps: ['Confirm requirements and licensing.', 'Test compatibility and security.', 'Pilot with rollback.', 'Deploy in stages.', 'Measure and support.'], model: 'Inventory targets, validate requirements and licensing, package through approved management tooling, test in a lab and pilot group, define rollback and communications, stage deployment, monitor failures, and reconcile results.' }
  ], featuredScenario: 'Can you isolate the fault before replacing a part?',
  console: { label: 'A+ QUICK CHECK', command: 'symptom: one user, one device, one application', lines: ['compare another user', 'compare another device', 'change one variable'], explanationLabel: 'WHY THIS MATTERS', explanation: 'Scope and controlled comparisons locate the failing layer faster than random replacement.' }
})

export const comptiaNetworkPlusRole = buildTrack({
  id: 'comptia-network-plus-n10-009', family: 'COMPTIA INFRASTRUCTURE', title: 'CompTIA Network+', shortTitle: 'Network+',
  subtitle: 'N10-009 networking foundations and troubleshooting', level: 'Beginner to intermediate', duration: '14–18 hours',
  description: 'Learn network models, addressing, routing, switching, wireless, cloud connectivity, operations, security, and structured troubleshooting for N10-009.',
  heroTitle: 'Understand how networks move data.', heroDescription: 'Build a mental model from cables and frames through IP routing, services, security, monitoring, and fault isolation. Every lesson begins in plain English and ends with practical reasoning.',
  exam: { version: 'N10-009', questions: 'Up to 90', minutes: 90, passDisplay: '720 / 900', format: 'Multiple choice + performance-based' },
  domains: [
    domain('Network Models & Traffic Flow', 'Follow data through layers, devices, addresses, protocols, and encapsulation.', [
      concept('OSI model', 'The seven-layer OSI model separates physical transmission, frames, packets, transport, sessions, presentation, and applications for design and troubleshooting.', 'a link-light failure is investigated at Layer 1 before DNS at Layer 7.', 'treating the model as traffic that literally passes through seven physical boxes'),
      concept('TCP and UDP', 'TCP provides connection-oriented reliable delivery, while UDP favors low overhead and timeliness without built-in delivery guarantees.', 'a file transfer values ordered reliable delivery while live voice can tolerate some loss.', 'assuming UDP is always faster or TCP is always better'),
      concept('Frames, packets, and segments', 'Data units change as information is encapsulated: Ethernet frames carry network packets, which carry transport data.', 'a switch forwards frames by MAC address while a router forwards packets by IP.', 'using frame and packet as identical terms in every context'),
      concept('Unicast, multicast, broadcast, anycast', 'Traffic delivery models target one receiver, a subscribed group, all hosts in a broadcast domain, or the nearest suitable service instance.', 'an IPv4 ARP request uses local broadcast while streaming distribution may use multicast.', 'assuming broadcasts cross routers by default')
    ]),
    domain('Addressing, Subnetting & Services', 'Configure IPv4 and IPv6, subnets, gateways, DHCP, DNS, NAT, and common ports.', [
      concept('IPv4 subnetting', 'A subnet mask or prefix divides an IPv4 address into network and host portions, defining local range and broadcast boundaries.', 'a /24 provides 256 addresses and normally 254 usable host addresses.', 'subtracting addresses without accounting for network and broadcast'),
      concept('IPv6', 'IPv6 uses 128-bit hexadecimal addressing, supports link-local operation, and replaces broadcast with multicast and other mechanisms.', 'a fe80:: link-local address communicates on the local link but is not routed normally.', 'shortening IPv6 by removing more than one run of zero groups'),
      concept('DHCP', 'DHCP leases addressing configuration through discovery, offer, request, and acknowledgment, with relay supporting remote subnets.', 'clients on one VLAN reach a centralized DHCP server through an IP helper.', 'expecting DNS to assign client IP addresses'),
      concept('DNS', 'DNS resolves hierarchical names using record types, recursive resolvers, authoritative servers, and caching.', 'an A record maps a name to IPv4 while a CNAME creates an alias.', 'using a CNAME at a zone apex without checking provider behavior')
    ]),
    domain('Routing, Switching & Segmentation', 'Understand Layer 2 forwarding, VLANs, trunks, loops, routes, redundancy, and traffic control.', [
      concept('MAC switching', 'A switch learns source MAC addresses and forwards frames using its MAC table within a Layer 2 domain.', 'an unknown unicast is flooded within the VLAN until the destination is learned.', 'assuming a Layer 2 switch chooses paths from IP routing tables'),
      concept('VLANs and trunks', 'VLANs create logical Layer 2 broadcast domains; tagged trunks carry multiple VLANs between compatible devices.', 'user and voice traffic share a link but remain logically separated by tags.', 'assuming VLANs provide complete security without routing and policy controls'),
      concept('Routing tables', 'Routers select the most specific matching route, then consider route source and metric according to platform rules.', 'a /24 route wins over a /16 route for a matching destination.', 'choosing the route with the smallest written network address'),
      concept('Loop prevention and redundancy', 'Spanning Tree blocks redundant Layer 2 paths to prevent loops while retaining failover potential.', 'a topology change activates a backup link without allowing broadcast storms.', 'disabling loop prevention because redundant links seem faster')
    ]),
    domain('Wireless & Physical Infrastructure', 'Select media, connectors, wireless bands, channels, antennas, and placement.', [
      concept('Copper and fiber', 'Copper Ethernet is practical for shorter runs and power delivery, while fiber supports distance, bandwidth, and resistance to electromagnetic interference.', 'fiber connects buildings where lightning and distance make copper unsuitable.', 'selecting multimode or single-mode optics without matching fiber and distance'),
      concept('Transceivers and connectors', 'Interfaces require compatible speeds, wavelengths, fiber types, connectors, and transceiver standards.', 'an SFP+ optic and patch cable are matched to the switch, remote optic, and link budget.', 'forcing physically fitting but electrically or optically incompatible parts'),
      concept('Wireless bands and channels', '2.4, 5, and 6 GHz bands trade range, penetration, channel availability, interference, and client support.', '2.4 GHz may reach farther while 5 or 6 GHz offers more clean channel capacity.', 'setting every nearby access point to the same channel'),
      concept('Wireless design', 'Wireless design considers coverage, capacity, interference, roaming, antenna patterns, power, channel width, and site-survey evidence.', 'a high-density room uses more carefully planned cells rather than one maximum-power AP.', 'treating signal strength alone as proof of adequate performance')
    ]),
    domain('Cloud, Virtual & Data Center Networking', 'Connect virtual workloads, cloud services, storage, and modern network functions.', [
      concept('Virtual switching', 'Virtual switches connect VMs and uplinks using logical ports, VLANs, and policies similar to physical switching.', 'two VMs on one host may exchange traffic without reaching a physical switch.', 'assuming all virtual traffic is visible on the physical access switch'),
      concept('Software-defined networking', 'SDN separates centralized or software-driven control from distributed forwarding to improve programmability and consistency.', 'a controller applies policy across many network devices through APIs.', 'assuming SDN removes physical network hardware'),
      concept('Cloud connectivity', 'Cloud networks use virtual subnets, route tables, gateways, security controls, VPNs, and dedicated links under shared responsibility.', 'a private workload reaches on-premises systems through an encrypted site-to-site VPN.', 'assuming a public cloud subnet is automatically reachable from the internet'),
      concept('Load balancing', 'Load balancers distribute requests across healthy targets using algorithms, health checks, persistence, and Layer 4 or Layer 7 awareness.', 'unhealthy application instances are removed from rotation after failed checks.', 'using DNS round robin as equivalent to every load-balancer capability')
    ]),
    domain('Network Operations', 'Document, monitor, baseline, maintain, and recover network services.', [
      concept('Network documentation', 'Diagrams, inventories, IP plans, configurations, dependencies, circuits, contacts, and change records reduce recovery time and risk.', 'a logical diagram shows VLANs and routing while a physical diagram shows ports and cabling.', 'keeping critical topology knowledge only in one engineer’s memory'),
      concept('Monitoring and baselines', 'Monitoring collects availability, performance, flow, logs, and events; a baseline defines normal behavior for comparison.', 'an alert compares interface errors and latency with normal time-of-day patterns.', 'treating one high utilization sample as proof of persistent saturation'),
      concept('High availability', 'Redundancy, failover, clustering, load balancing, diverse paths, backups, and tested recovery reduce single points of failure.', 'dual providers use physically diverse entrances and validated failover.', 'buying duplicate devices without testing state, routing, or dependency failover'),
      concept('Change and configuration management', 'Network changes require versioned configurations, assessment, approval, communication, rollback, validation, and updated documentation.', 'a switch upgrade is backed up, piloted, scheduled, monitored, and reversible.', 'editing production devices without recording the prior state')
    ]),
    domain('Network Security', 'Protect network access, management, segmentation, traffic, and services.', [
      concept('Segmentation', 'Segmentation limits reachability and blast radius using VLANs, subnets, firewalls, ACLs, zones, and identity-aware policy.', 'guest wireless reaches the internet but cannot initiate traffic to internal servers.', 'assuming VLAN separation alone enforces all required access control'),
      concept('Access control lists', 'ACLs permit or deny traffic based on ordered criteria; placement and implicit-deny behavior affect results.', 'a specific required service is permitted before a broader deny rule.', 'placing an allow rule after traffic has already matched a deny'),
      concept('Network authentication', '802.1X and centralized AAA can authenticate users or devices before granting wired or wireless access.', 'a switch uses RADIUS to assign an authorized endpoint to an appropriate network.', 'relying only on a switch port being physically inside the office'),
      concept('Secure management', 'Management planes use encrypted protocols, dedicated access, MFA, least privilege, logging, backups, and restricted source networks.', 'SSH and HTTPS replace Telnet and HTTP for device administration.', 'exposing management interfaces to the public internet for convenience')
    ]),
    domain('Network Troubleshooting', 'Use scope, layers, evidence, tests, and validation to isolate connectivity and performance faults.', [
      concept('Troubleshooting methodology', 'A repeatable method defines the problem, establishes a theory, tests safely, plans action, implements, verifies, and documents.', 'a technician identifies whether failure affects one host, VLAN, site, or service before changing settings.', 'starting with the most disruptive possible change'),
      concept('Layered tests', 'Tools such as link status, ping, traceroute, ARP, route tables, DNS queries, packet capture, and logs answer different layer questions.', 'successful ping by IP but failed name lookup directs attention to DNS.', 'assuming failed ping proves the destination is offline despite possible filtering'),
      concept('Performance faults', 'Latency, jitter, loss, congestion, errors, duplex issues, interference, and resource limits produce different patterns.', 'voice breaks up during variable delay and loss even though average bandwidth looks sufficient.', 'treating bandwidth and latency as the same measurement'),
      concept('Physical fault isolation', 'Known-good cables, loopbacks, light levels, interface counters, pinouts, and swap tests isolate media and port faults.', 'increasing CRC errors prompts checks for cabling, optics, interference, and duplex.', 'clearing counters without recording the evidence')
    ])
  ],
  scenarios: [
    { title: 'No address after office move', prompt: 'A workstation shows a 169.254 address after being moved to another desk.', steps: ['Check link and VLAN.', 'Inspect DHCP path.', 'Compare a known-good device.', 'Renew after correcting the cause.', 'Validate gateway, DNS, and application access.'], model: 'The address suggests DHCP did not complete. Check cable, switch port state and VLAN, DHCP scope and relay, then compare another device. Avoid assigning a random static address that could conflict.' },
    { title: 'Voice quality degrades', prompt: 'Calls become choppy every afternoon while ordinary web browsing still works.', steps: ['Establish timing and scope.', 'Measure loss, latency, and jitter.', 'Check queues and utilization.', 'Inspect wireless or WAN dependencies.', 'Validate a controlled improvement.'], model: 'Correlate call quality with interface utilization, QoS queues, loss, jitter, and path changes. Web traffic tolerates delay better than real-time voice, so “the internet works” does not clear the network.' },
    { title: 'New VLAN cannot reach DNS', prompt: 'Clients receive addresses and reach their gateway but cannot query the central DNS server.', steps: ['Confirm addressing and route.', 'Test IP reachability.', 'Inspect ACL and firewall order.', 'Verify DNS service binding.', 'Document the dependency.'], model: 'Because DHCP and the gateway work, follow the routed path to DNS, check return routing and ordered policy, verify port 53 over required transports, and inspect server-side listening and logs.' },
    { title: 'Intermittent fiber uplink', prompt: 'A switch uplink flaps several times per day and logs receive errors.', steps: ['Preserve counters and timestamps.', 'Check both ends.', 'Verify optic and fiber compatibility.', 'Measure or clean safely.', 'Replace one controlled element and monitor.'], model: 'Match optics, wavelength, fiber type, connectors, speed, and distance; inspect and clean using approved procedures; check light levels and counters at both ends; then replace one known-good component at a time.' }
  ], featuredScenario: 'Can you find the failing layer before changing the network?',
  console: { label: 'NETWORK+ QUICK CHECK', command: 'works by IP · fails by name', lines: ['reachability exists', 'test resolver and records', 'inspect DNS path and cache'], explanationLabel: 'FAULT DOMAIN', explanation: 'A successful IP test narrows the problem; it does not prove every application layer is healthy.' }
})

export const comptiaSecurityPlusRole = buildTrack({
  id: 'comptia-security-plus-sy0-701', family: 'COMPTIA CYBERSECURITY', title: 'CompTIA Security+', shortTitle: 'Security+',
  subtitle: 'SY0-701 security foundations and operations', level: 'Beginner to intermediate', duration: '16–20 hours',
  description: 'Learn security principles, threats, architecture, identity, cryptography, vulnerability management, incident response, governance, risk, and resilience for SY0-701.',
  heroTitle: 'Build security judgment, not just vocabulary.', heroDescription: 'Learn how to reduce likelihood and impact through layered controls, evidence, responsible response, and business-aligned risk decisions. No cybersecurity experience is assumed.',
  exam: { version: 'SY0-701', questions: 'Up to 90', minutes: 90, passDisplay: '750 / 900', format: 'Multiple choice + performance-based' },
  domains: [
    domain('Core Security Principles', 'Use confidentiality, integrity, availability, non-repudiation, control types, and zero-trust thinking.', [
      concept('CIA triad', 'Confidentiality prevents unauthorized disclosure, integrity prevents unauthorized change, and availability keeps resources usable when needed.', 'encryption protects confidentiality while hashes help detect integrity changes.', 'assuming one control provides all three properties equally'),
      concept('Authentication and authorization', 'Authentication verifies identity, while authorization determines what an authenticated principal may do.', 'MFA proves a user identity before role-based policy grants access to payroll.', 'granting permissions simply because a password was accepted'),
      concept('Zero trust', 'Zero trust assumes no implicit trust based on location and continuously evaluates identity, device, context, least privilege, and resource policy.', 'an internal device still needs strong identity and health checks for a sensitive application.', 'treating zero trust as one product or blocking all communication'),
      concept('Control categories and types', 'Controls can be managerial, operational, technical, or physical and can prevent, deter, detect, correct, compensate, or direct.', 'a camera detects and deters while a locked door physically prevents entry.', 'labeling every written policy as a technical preventive control')
    ]),
    domain('Threats & Social Engineering', 'Recognize actors, motivations, attack surfaces, phishing, impersonation, and malicious influence.', [
      concept('Threat actors', 'Nation-states, criminals, insiders, activists, competitors, and unskilled attackers differ in motivation, resources, access, and persistence.', 'a financially motivated group deploys ransomware while espionage may prioritize stealth.', 'assuming attribution from one tool or language clue'),
      concept('Phishing', 'Phishing uses deceptive communication to steal information, deliver malware, or influence action through email, text, voice, QR codes, or targeted messages.', 'a payment-change request is verified through a known independent channel.', 'trusting a message because it includes company branding'),
      concept('Social engineering', 'Social engineering manipulates trust, urgency, authority, fear, curiosity, or helpfulness to bypass technical and procedural controls.', 'a caller claiming executive urgency is still required to follow identity and approval procedures.', 'treating awareness training as a replacement for technical controls'),
      concept('Supply-chain risk', 'Supply-chain attacks compromise trusted software, hardware, services, updates, or providers to reach downstream targets.', 'signed packages, supplier assessment, isolation, monitoring, and integrity checks reduce update risk.', 'assuming a trusted vendor can never be a threat path')
    ]),
    domain('Vulnerabilities & Mitigations', 'Understand weaknesses, scanning, patching, secure configuration, application flaws, and compensating controls.', [
      concept('Vulnerability management', 'Vulnerability management continuously discovers, assesses, prioritizes, remediates, validates, and reports weaknesses using asset and threat context.', 'an internet-facing exploited flaw is prioritized above a low-impact isolated finding.', 'sorting only by raw scanner severity without business context'),
      concept('Common application flaws', 'Injection, cross-site scripting, broken access control, insecure design, and vulnerable dependencies require secure design, validation, testing, and updates.', 'parameterized queries help prevent SQL injection by separating code from data.', 'trying to block every application flaw only at the network perimeter'),
      concept('Hardening', 'Hardening reduces attack surface through secure baselines, least functionality, patches, configuration, segmentation, and continuous validation.', 'unused services and default accounts are disabled before production deployment.', 'applying a baseline without testing business requirements'),
      concept('Compensating controls', 'A compensating control provides alternative risk reduction when the preferred control is not currently feasible.', 'a legacy system that cannot be patched is isolated, tightly monitored, and access-restricted.', 'calling a workaround permanent risk acceptance without review')
    ]),
    domain('Secure Architecture', 'Design segmentation, resilience, cloud, endpoints, data protection, and trust boundaries.', [
      concept('Defense in depth', 'Defense in depth layers complementary preventive, detective, and corrective controls so one failure does not expose the asset.', 'MFA, endpoint protection, segmentation, logging, backups, and response plans protect a critical service.', 'deploying several copies of the same control with the same weakness'),
      concept('Segmentation and isolation', 'Segmentation limits reachability and blast radius through zones, firewalls, ACLs, microsegmentation, and separate trust levels.', 'payment systems accept only required flows from controlled application tiers.', 'placing systems in different VLANs without enforcing policy between them'),
      concept('Resilience and recovery', 'Resilience combines redundancy, diversity, backups, recovery objectives, testing, alternate facilities, and practiced procedures.', 'offline immutable backups are restored during exercises to validate recovery time.', 'assuming a successful backup job guarantees recoverability'),
      concept('Shared responsibility', 'Cloud providers and customers divide security duties according to the service model, contract, configuration, and data ownership.', 'a SaaS provider operates infrastructure while the customer manages users, access, and data policy.', 'assuming migration to cloud transfers every security obligation')
    ]),
    domain('Identity & Cryptography', 'Apply identity lifecycle, federation, MFA, certificates, encryption, hashing, and key management.', [
      concept('Identity lifecycle', 'Identities and privileges are requested, approved, provisioned, reviewed, changed, and removed as roles and relationships change.', 'departing-user access is revoked promptly and privileged accounts are reconciled.', 'creating shared accounts to avoid lifecycle administration'),
      concept('Federation and SSO', 'Federation establishes trust across identity domains, while single sign-on lets a user authenticate once to access multiple authorized resources.', 'an organization uses a trusted identity provider to access a cloud service.', 'assuming SSO eliminates the consequences of credential compromise'),
      concept('Encryption and hashing', 'Encryption is reversible with a key to protect confidentiality; hashing is one-way and supports integrity and password verification.', 'passwords are stored with a slow salted password-hashing function.', 'encrypting passwords with a shared recoverable key as the default storage method'),
      concept('Public key infrastructure', 'PKI manages certificates, public/private keys, certificate authorities, revocation, and trust for identity and secure communication.', 'a browser validates a server certificate chain and hostname before establishing TLS.', 'trusting any self-signed certificate without an established trust decision')
    ]),
    domain('Security Operations', 'Monitor, log, detect, prioritize alerts, manage endpoints, and respond to suspicious activity.', [
      concept('Security monitoring', 'Monitoring correlates logs, telemetry, network activity, identity events, endpoint data, and threat context to detect meaningful behavior.', 'a SIEM links impossible travel with a new device and unusual data access.', 'treating every alert as a confirmed incident'),
      concept('Endpoint security', 'Endpoint controls include secure configuration, EDR, anti-malware, host firewalls, encryption, application control, patching, and device management.', 'EDR isolates a host while preserving investigation evidence.', 'assuming antivirus signatures stop every attack technique'),
      concept('Data loss prevention', 'DLP identifies and controls sensitive data movement according to classification, context, channel, and policy.', 'a rule blocks regulated data from being emailed externally and alerts an owner.', 'using DLP without classification, tuning, exception, or privacy processes'),
      concept('Automation and orchestration', 'Security automation executes repeatable actions, while orchestration coordinates tools and workflows with controls and human approval where needed.', 'a phishing workflow enriches indicators and disables a malicious link after validation.', 'automatically deleting evidence or accounts on every unverified alert')
    ]),
    domain('Incident Response & Forensics', 'Prepare, detect, analyze, contain, eradicate, recover, communicate, and learn while preserving evidence.', [
      concept('Incident response lifecycle', 'Response preparation enables detection, analysis, containment, eradication, recovery, lessons learned, and communication.', 'a ransomware playbook identifies decision authority, isolation steps, evidence, restoration, and notifications.', 'starting eradication before understanding scope and preserving evidence'),
      concept('Containment', 'Containment limits ongoing harm while balancing evidence, business continuity, safety, and attacker awareness.', 'a compromised endpoint is network-isolated through EDR without immediately wiping it.', 'powering off every system automatically regardless of forensic needs'),
      concept('Chain of custody', 'Chain of custody records who collected, handled, transferred, stored, and analyzed evidence with integrity and timestamps.', 'a disk image hash and transfer log demonstrate evidence remained unchanged.', 'copying evidence to an untracked personal drive'),
      concept('Recovery and lessons learned', 'Recovery restores trusted operations, monitors for recurrence, communicates status, and turns findings into corrective actions.', 'clean systems are restored, credentials rotated, controls improved, and owners assigned follow-up work.', 'closing the incident as soon as one server is online')
    ]),
    domain('Governance, Risk & Compliance', 'Connect policies, risk decisions, third parties, privacy, audits, awareness, and continuity to business objectives.', [
      concept('Risk assessment', 'Risk assessment identifies assets, threats, vulnerabilities, likelihood, impact, existing controls, and residual exposure to support decisions.', 'leaders compare mitigation cost and business impact before choosing treatment.', 'claiming a precise probability without reliable data or assumptions'),
      concept('Risk treatment', 'Organizations may mitigate, transfer, avoid, or accept risk through authorized, documented decisions and ongoing review.', 'a business purchases insurance for part of the financial impact while still reducing likelihood.', 'calling ignored risk accepted without an accountable owner'),
      concept('Policies, standards, and procedures', 'Policies state management intent, standards define mandatory requirements, procedures give steps, and guidelines offer recommendations.', 'a password policy is supported by a technical standard and account-creation procedure.', 'using one vague document for every level of direction'),
      concept('Third-party risk', 'Third-party risk management evaluates selection, contracts, access, security evidence, monitoring, incident duties, continuity, and termination.', 'a supplier’s access is least-privileged, logged, reviewed, and removed at contract end.', 'assuming a contract transfers accountability for stakeholder harm')
    ])
  ],
  scenarios: [
    { title: 'Possible account takeover', prompt: 'A user account signs in from a new country and downloads unusual volumes of data.', steps: ['Validate the signal.', 'Contain identity and sessions.', 'Preserve logs.', 'Determine scope.', 'Recover and improve controls.'], model: 'Correlate identity, device, network, and application evidence; revoke suspicious sessions and reset credentials through verified channels; preserve logs; inspect lateral access and data exposure; apply notifications and lessons according to policy.' },
    { title: 'Critical legacy vulnerability', prompt: 'A production system has an exploited vulnerability but cannot be patched for six weeks.', steps: ['Assess asset and exposure.', 'Identify threat activity.', 'Apply compensating controls.', 'Set accountable acceptance and deadline.', 'Monitor and validate.'], model: 'Segment and restrict access, disable unnecessary functions, add detection, protect credentials, consider virtual patching, document residual risk with an authorized owner, accelerate replacement, and monitor for exploitation.' },
    { title: 'Ransomware on one endpoint', prompt: 'EDR reports encryption behavior on a finance workstation.', steps: ['Contain safely.', 'Preserve evidence.', 'Search for wider indicators.', 'Eradicate and recover from trusted sources.', 'Communicate and learn.'], model: 'Isolate through EDR, notify the response team, protect volatile and persistent evidence according to procedure, hunt across identity and endpoints, block indicators, rebuild or remediate from trust, restore validated data, rotate affected credentials, and document lessons.' },
    { title: 'New SaaS supplier', prompt: 'A department wants to store customer data in a new SaaS application next week.', steps: ['Classify data and requirements.', 'Assess supplier controls and contract.', 'Design identity and access.', 'Plan logging, recovery, and exit.', 'Approve according to risk.'], model: 'Review data classification, privacy, residency, encryption, identity integration, least privilege, audit evidence, incident notification, availability, backup and export, subcontractors, and termination before authorized use.' }
  ], featuredScenario: 'Can you reduce harm without destroying the evidence?',
  console: { label: 'SECURITY+ QUICK CHECK', command: 'alert ≠ incident', lines: ['validate evidence', 'assess scope and impact', 'contain with authority'], explanationLabel: 'SECURITY JUDGMENT', explanation: 'Fast response matters, but unverified destructive action can increase harm and erase evidence.' }
})

export const comptiaLinuxPlusRole = buildTrack({
  id: 'comptia-linux-plus-xk0-006', family: 'COMPTIA INFRASTRUCTURE', title: 'CompTIA Linux+', shortTitle: 'Linux+',
  subtitle: 'XK0-006 Linux administration, automation, and security', level: 'Intermediate', duration: '16–20 hours',
  description: 'Learn Linux installation, command line, storage, networking, services, security, scripting, containers, automation, and troubleshooting for XK0-006.',
  heroTitle: 'Operate Linux with confidence.', heroDescription: 'Move from filesystem fundamentals to secure services, automation, containers, and evidence-driven troubleshooting using commands you can practice in a safe virtual lab.',
  exam: { version: 'XK0-006', questions: 'Up to 90', minutes: 90, passDisplay: '720 / 900', format: 'Multiple choice + performance-based' },
  domains: [
    domain('Shell & Filesystem Fundamentals', 'Navigate, manipulate, search, redirect, and protect files from the command line.', [
      concept('Filesystem hierarchy', 'Linux organizes files under a single root with conventional locations such as /etc for configuration, /var for changing data, /home for users, and /proc for kernel views.', 'a service configuration is sought under /etc while its logs are inspected under /var/log.', 'assuming drive letters define separate filesystem roots'),
      concept('Permissions', 'Owner, group, and other read/write/execute bits plus special modes and ACLs control filesystem access.', 'chmod changes mode while chown changes ownership and getfacl reveals extended rules.', 'granting world-write access to solve an ownership problem'),
      concept('Pipes and redirection', 'Standard input, output, and error can be redirected and connected so small commands form repeatable workflows.', 'journal output is filtered with grep and saved while errors go to a separate file.', 'using overwrite redirection when append was intended'),
      concept('Text processing', 'Tools such as grep, sed, awk, cut, sort, uniq, head, tail, and regular expressions extract and transform text.', 'awk summarizes a selected log field after grep narrows relevant records.', 'editing original configuration data without backup or validation')
    ]),
    domain('Installation, Packages & Boot', 'Manage distributions, repositories, software, kernels, services, bootloaders, and startup.', [
      concept('Package management', 'Distribution package tools install signed software, resolve dependencies, track files, and use configured repositories.', 'apt or dnf installs from trusted repositories and records package state.', 'downloading random binaries instead of using verified sources'),
      concept('Systemd', 'Systemd manages units, dependencies, startup targets, services, timers, and logs on many distributions.', 'systemctl status and journalctl inspect why a service failed before restart.', 'restarting repeatedly without reading unit logs'),
      concept('Boot process', 'Firmware starts a bootloader, which loads the kernel and initramfs before the init system starts user-space services.', 'a missing root filesystem driver is investigated in initramfs and kernel messages.', 'blaming a login shell for failure before the kernel loads'),
      concept('Kernel and modules', 'The kernel manages hardware and core resources; loadable modules add drivers and features with parameters and compatibility requirements.', 'lsmod and modprobe inspect and load a supported network driver.', 'installing an unrelated user-space package for every hardware failure')
    ]),
    domain('Storage & Data', 'Partition, format, mount, manage volumes, quotas, RAID, backups, and shared storage.', [
      concept('Partitions and filesystems', 'Block devices are partitioned, formatted with filesystems, mounted into the directory tree, and identified persistently by UUID or labels.', 'an /etc/fstab entry uses UUID and is tested with mount before reboot.', 'using a changing device name without validation'),
      concept('LVM', 'Logical Volume Manager combines physical volumes into volume groups and allocates flexible logical volumes.', 'a logical volume and filesystem are extended after confirming free extents and backup.', 'assuming extending a block device automatically grows every filesystem'),
      concept('RAID', 'RAID combines disks for performance, capacity, or redundancy, but does not replace independent backups.', 'a degraded mirror continues operation while a failed disk is replaced and rebuild monitored.', 'treating RAID as protection from deletion or ransomware'),
      concept('Backup and restore', 'Backups need defined scope, retention, protection, monitoring, and regular restore testing against recovery objectives.', 'a configuration backup is restored in a test VM and compared with expected state.', 'equating a successful copy job with proven recovery')
    ]),
    domain('Networking & Services', 'Configure interfaces, routes, DNS, firewalls, time, remote access, and common network services.', [
      concept('Linux networking', 'Addresses, routes, DNS resolvers, links, sockets, and interface state are inspected with tools such as ip, ss, resolvectl, ping, and traceroute.', 'ip route reveals a missing default route while ss confirms a service is listening.', 'using ifconfig output alone as proof of end-to-end reachability'),
      concept('SSH', 'SSH provides encrypted remote login, command execution, tunneling, and file transfer with host and user key trust.', 'key-based access is restricted and host fingerprints are verified.', 'disabling host-key checking to remove every warning'),
      concept('Host firewall', 'nftables or frontend tools enforce ordered stateful traffic policy at the host boundary.', 'only required management sources can reach SSH and the rule persists after reboot.', 'adding a broad allow rule before understanding rule order'),
      concept('Time and name resolution', 'Accurate time supports authentication and logs, while resolver configuration translates names and search domains.', 'authentication failures are correlated with clock drift and NTP status.', 'editing hosts files as a permanent substitute for healthy DNS')
    ]),
    domain('Identity & Security', 'Manage accounts, privilege, authentication, logging, mandatory controls, encryption, and hardening.', [
      concept('Users and groups', 'Linux identities use UIDs, GIDs, account databases, home directories, shells, group membership, and lifecycle controls.', 'a service gets a non-login account with only required file ownership.', 'reusing one administrator account across people'),
      concept('Sudo and privilege', 'Sudo delegates specific privileged commands with policy and logging instead of routine root sessions.', 'an operations group can restart one service without unrestricted shell access.', 'granting NOPASSWD access to every command'),
      concept('SELinux and AppArmor', 'Mandatory access controls constrain processes beyond traditional file permissions using labels or profiles and logged denials.', 'a service denial is diagnosed from audit evidence before changing policy.', 'disabling enforcement permanently to hide a labeling error'),
      concept('Logging and auditing', 'System journals, application logs, rotation, remote collection, audit rules, time sync, and integrity protect operational evidence.', 'privileged actions are forwarded to a restricted central log service.', 'letting a full log filesystem interrupt production')
    ]),
    domain('Scripting & Automation', 'Write safe shell logic, schedule work, manage configuration, use version control, and automate repeatably.', [
      concept('Shell scripting', 'Shell scripts combine variables, quoting, tests, loops, functions, exit codes, and error handling for repeatable administration.', 'a script validates input and exits nonzero when a backup fails.', 'ignoring spaces and special characters through unsafe expansion'),
      concept('Scheduling', 'Cron and systemd timers run recurring work with environment, identity, logging, concurrency, and failure considerations.', 'a timer records output and alerts when a maintenance job fails.', 'assuming an interactive shell environment exists in scheduled work'),
      concept('Configuration management', 'Configuration-management tools declare desired state and apply idempotent changes across systems with inventory and version control.', 'a playbook ensures a package, file, and service state consistently.', 'using automation to repeat an untested destructive command faster'),
      concept('Git fundamentals', 'Version control records changes, branches, reviews, merges, and rollback context for code and configuration.', 'an infrastructure change is reviewed through a pull request before deployment.', 'committing secrets or generated credentials to a repository')
    ]),
    domain('Containers & Orchestration', 'Understand images, containers, registries, storage, networking, Kubernetes objects, and secure operation.', [
      concept('Container images', 'Images are layered immutable templates built from instructions and stored in registries with tags and digests.', 'production pins a reviewed image digest rather than an ambiguous latest tag.', 'treating an image signature as proof it contains no vulnerability'),
      concept('Container runtime', 'A runtime creates isolated processes using namespaces, control groups, filesystems, networking, and security settings.', 'a service runs as a non-root user with limited capabilities and resources.', 'assuming containers create the same isolation boundary as separate hardware'),
      concept('Persistent storage and networking', 'Container data and connectivity require explicit volumes, networks, ports, service discovery, and lifecycle planning.', 'state is stored in a managed volume rather than the writable container layer.', 'expecting deleted containers to preserve unmounted local data'),
      concept('Kubernetes basics', 'Kubernetes reconciles declared objects such as pods, deployments, services, configuration, secrets, and storage across a cluster.', 'a deployment replaces failed pods while a service gives stable discovery.', 'editing a running pod manually as the durable desired state')
    ]),
    domain('Linux Troubleshooting', 'Diagnose boot, performance, storage, network, service, and security failures from evidence.', [
      concept('Resource troubleshooting', 'CPU, memory, I/O, load, processes, pressure, and limits are correlated over time before action.', 'high load with low CPU prompts investigation of blocked I/O rather than adding processors.', 'treating load average as CPU percentage'),
      concept('Disk and filesystem faults', 'Capacity, inodes, mounts, permissions, device errors, filesystem health, and open deleted files can all cause storage symptoms.', 'df and du differ because a process still holds a deleted log open.', 'deleting random files before identifying ownership and retention'),
      concept('Service failure analysis', 'Unit state, dependencies, configuration syntax, permissions, ports, logs, security controls, and recent changes narrow service failures.', 'a failed web service is checked with systemctl, journalctl, config test, ss, and audit logs.', 'reinstalling the package before preserving the failing configuration'),
      concept('Boot recovery', 'Recovery uses console access, bootloader options, emergency targets, filesystem checks, initramfs repair, and known-good kernels with data protection.', 'a recent kernel failure is tested with a known-good boot entry before removal.', 'running filesystem repair on a mounted active filesystem without procedure')
    ])
  ],
  scenarios: [
    { title: 'Service will not start', prompt: 'A web service fails immediately after a configuration change.', steps: ['Record the change.', 'Inspect unit status and journal.', 'Run configuration validation.', 'Check permissions, ports, and security denials.', 'Rollback or correct and validate.'], model: 'Preserve the changed file, inspect systemctl status and journalctl, run the service’s syntax test, compare permissions and listening ports, check SELinux or AppArmor evidence, then correct or rollback one change and validate locally and remotely.' },
    { title: 'Root filesystem full', prompt: 'Applications fail and / reports 100% usage.', steps: ['Protect service and evidence.', 'Check blocks and inodes.', 'Find large and deleted-open files.', 'Manage logs safely.', 'Prevent recurrence.'], model: 'Use df for blocks and inodes, du within the same filesystem, lsof for deleted-open files, and journal or log policies. Do not blindly delete; identify the owner, rotate or truncate safely, restore headroom, and add monitoring.' },
    { title: 'SSH stopped working', prompt: 'A server is reachable by ping but remote SSH connections time out.', steps: ['Use console or alternate access.', 'Check service and socket.', 'Inspect host firewall and upstream path.', 'Review logs and recent changes.', 'Validate securely.'], model: 'Ping only proves some Layer 3 path. Check sshd state and configuration, listening address and port, host and network policy, route and return path, authentication logs, and recent change history.' },
    { title: 'Container loses data', prompt: 'Application data disappears whenever a container is recreated.', steps: ['Identify writable locations.', 'Inspect volume mounts.', 'Separate image from state.', 'Restore and validate data.', 'Update deployment declaration.'], model: 'The writable container layer is ephemeral. Store durable state in a declared volume or external service, set ownership and backup, restore validated data, and update version-controlled deployment configuration.' }
  ], featuredScenario: 'Can you use evidence before restarting the service?',
  console: { label: 'LINUX+ QUICK CHECK', command: 'systemctl status app', lines: ['journalctl -u app', 'ss -lntp', 'validate config before restart'], explanationLabel: 'ADMIN HABIT', explanation: 'State, logs, sockets, and configuration tests turn a vague failure into a testable hypothesis.' }
})

export const comptiaCloudPlusRole = buildTrack({
  id: 'comptia-cloud-plus-cv0-004', family: 'COMPTIA INFRASTRUCTURE', title: 'CompTIA Cloud+', shortTitle: 'Cloud+',
  subtitle: 'CV0-004 cloud infrastructure, security, and operations', level: 'Intermediate', duration: '16–20 hours',
  description: 'Learn vendor-neutral cloud architecture, deployment, operations, security, DevOps foundations, resilience, cost, automation, and troubleshooting for CV0-004.',
  heroTitle: 'Operate cloud services as systems.', heroDescription: 'Understand shared responsibility, virtual networks, compute, storage, identity, automation, observability, resilience, and cost across public, private, hybrid, and multicloud environments.',
  exam: { version: 'CV0-004', questions: 'Up to 90', minutes: 90, passDisplay: '750 / 900', format: 'Multiple choice + performance-based' },
  domains: [
    domain('Cloud Concepts & Architecture', 'Understand service models, deployment models, shared responsibility, regions, zones, and design tradeoffs.', [
      concept('Service models', 'IaaS, PaaS, and SaaS shift different layers of infrastructure, platform, application, and security responsibility to the provider.', 'an IaaS customer patches guest operating systems while a SaaS customer manages users and data use.', 'assuming provider responsibility means customer accountability disappears'),
      concept('Deployment models', 'Public, private, hybrid, community, and multicloud designs differ in ownership, connectivity, governance, portability, and operational complexity.', 'a hybrid application connects on-premises data with public-cloud compute through controlled links.', 'using multicloud without a business requirement or operating model'),
      concept('Regions and availability zones', 'Regions are geographic areas containing isolated locations or zones used to design latency, residency, and failure boundaries.', 'an application spans zones for local resilience and another region for disaster recovery.', 'assuming two zones protect against every regional dependency'),
      concept('Elasticity and scalability', 'Scalability adds capacity for demand, while elasticity automatically expands and contracts resources in response to changing load.', 'an autoscaling group adds instances during a sales event and removes them afterward.', 'keeping maximum capacity running permanently and calling it elastic')
    ]),
    domain('Compute, Storage & Databases', 'Select virtual machines, containers, serverless, storage types, tiers, databases, and lifecycle controls.', [
      concept('Cloud compute', 'VMs, containers, managed platforms, and serverless functions offer different control, portability, startup, scaling, and operational responsibility.', 'a short event-driven task uses a function while a legacy OS workload uses a VM.', 'choosing serverless for a continuous unsupported workload without cost analysis'),
      concept('Object, block, and file storage', 'Object storage uses API-addressed objects, block storage presents volumes, and file storage provides shared hierarchical access.', 'a VM database uses low-latency block storage while static media uses object storage.', 'mounting object storage as if it has every POSIX filesystem behavior'),
      concept('Storage lifecycle', 'Tiering, retention, versioning, immutability, replication, encryption, and deletion policies balance cost, performance, recovery, and compliance.', 'old logs transition to an archive tier and expire according to approved retention.', 'moving frequently restored data to the cheapest slow archive tier'),
      concept('Database choices', 'Relational, key-value, document, graph, time-series, and managed database options fit different consistency, query, scaling, and operational needs.', 'a transactional ledger uses strong relational constraints while telemetry uses time-series storage.', 'selecting a database only because it is currently popular')
    ]),
    domain('Cloud Networking', 'Design virtual networks, subnets, routing, gateways, load balancing, DNS, private access, and hybrid links.', [
      concept('Virtual networks and subnets', 'Cloud virtual networks isolate address spaces and divide workloads into subnets with routes and policy boundaries.', 'public-facing load balancers sit in reachable subnets while databases remain private.', 'assuming a private IP alone blocks every unwanted path'),
      concept('Security groups and network ACLs', 'Stateful instance or interface controls and stateless subnet controls filter traffic at different scopes and require correct order and return handling.', 'a workload security group allows application traffic only from the load balancer identity.', 'opening all sources because one health check fails'),
      concept('Hybrid connectivity', 'VPNs and dedicated links connect sites and clouds with routing, encryption, redundancy, bandwidth, latency, and failover considerations.', 'redundant tunnels terminate on diverse devices and advertise controlled routes.', 'assuming one dedicated circuit provides automatic geographic resilience'),
      concept('Cloud load balancing and DNS', 'Load balancers and DNS policies distribute traffic by health, region, latency, weight, or application content.', 'failed targets leave rotation while DNS directs users to a healthy region.', 'setting DNS failover without considering caching and TTL')
    ]),
    domain('Deployment & Migration', 'Plan dependencies, landing zones, images, data transfer, cutover, rollback, validation, and modernization.', [
      concept('Landing zone', 'A landing zone establishes accounts, identity, networking, logging, security, policy, billing, and deployment guardrails before workloads scale.', 'new projects inherit centralized logging and least-privilege account structure.', 'letting each team invent unconnected cloud foundations'),
      concept('Migration strategies', 'Rehost, replatform, refactor, repurchase, retain, and retire represent different change, value, time, cost, and risk choices.', 'a deadline drives temporary rehosting followed by planned modernization.', 'refactoring every application before proving business value'),
      concept('Infrastructure as code', 'IaC declares versioned infrastructure that can be reviewed, tested, repeated, compared, and reconciled.', 'a pull request shows route and firewall changes before automated deployment.', 'editing production manually and leaving declared state outdated'),
      concept('Cutover and rollback', 'Migration cutover needs tested data synchronization, dependencies, freeze windows, communications, validation, decision points, and rollback.', 'a pilot and rehearsal prove restoration before DNS shifts production traffic.', 'discovering rollback requirements after the cutover starts')
    ]),
    domain('Cloud Operations & Observability', 'Monitor metrics, logs, traces, events, capacity, cost, configuration, backups, and service health.', [
      concept('Metrics, logs, and traces', 'Metrics show measured behavior, logs record events, and distributed traces follow requests across services; together they improve observability.', 'a latency metric triggers investigation and a trace locates the slow downstream call.', 'collecting telemetry without retention, ownership, or actionable alerts'),
      concept('Capacity and performance', 'Cloud performance depends on quotas, resource sizing, autoscaling, storage throughput, network limits, caching, and application design.', 'throttling is traced to an API quota rather than VM CPU.', 'adding larger instances before identifying the actual constraint'),
      concept('Cost management', 'Tags, budgets, allocation, rightsizing, schedules, commitments, lifecycle policies, and unit economics make cloud cost visible and controllable.', 'idle nonproduction systems stop on schedule while owners see cost per service.', 'optimizing only the monthly bill while harming reliability'),
      concept('Backup and disaster recovery', 'Cloud recovery requires protected backups, cross-boundary copies, defined RPO/RTO, dependencies, runbooks, credentials, and restore tests.', 'a regional exercise restores data and network dependencies in recovery order.', 'assuming provider durability replaces customer recovery planning')
    ]),
    domain('Cloud Security', 'Protect identity, data, keys, workloads, networks, posture, compliance, and secrets under shared responsibility.', [
      concept('Cloud IAM', 'Cloud IAM combines identities, roles, policies, federation, temporary credentials, MFA, and review to enforce least privilege.', 'a workload receives a short-lived role instead of a stored access key.', 'sharing one permanent administrator key across automation'),
      concept('Key and secret management', 'Managed key and secret systems control generation, storage, access, rotation, auditing, and separation from code.', 'a database password is fetched at runtime and rotated without committing it.', 'placing secrets in images, repositories, or startup logs'),
      concept('Cloud security posture', 'Posture management detects misconfiguration, excessive exposure, weak identity, unencrypted data, and drift against policies and benchmarks.', 'a public storage finding is validated, contained, investigated, and prevented through policy.', 'auto-remediating every finding without checking production impact'),
      concept('Data security and privacy', 'Classification, residency, encryption, tokenization, access, retention, deletion, and legal requirements follow data through its lifecycle.', 'regulated records stay in approved regions and access is logged and reviewed.', 'assuming encryption makes location and retention irrelevant')
    ]),
    domain('DevOps & Automation Fundamentals', 'Use source control, CI/CD, images, configuration, APIs, orchestration, and safe automated change.', [
      concept('CI/CD pipeline', 'A pipeline integrates build, test, security checks, packaging, approval, deployment, validation, and rollback into repeatable flow.', 'a failed security test prevents an artifact from progressing to production.', 'treating continuous deployment as deployment without controls'),
      concept('Artifacts and registries', 'Immutable packages, images, and artifacts are versioned, scanned, signed, stored, promoted, and retained through controlled repositories.', 'the same tested image digest moves from staging to production.', 'rebuilding a different artifact separately in production'),
      concept('APIs and event-driven systems', 'APIs expose controlled interfaces, while events enable asynchronous reactions that require authentication, contracts, idempotency, and failure handling.', 'a queue buffers events so a temporary consumer outage does not lose requests.', 'assuming asynchronous delivery occurs exactly once automatically'),
      concept('Automation safety', 'Safe automation uses scoped credentials, dry runs, tests, approvals, rate limits, logging, idempotency, rollback, and human control for high-impact actions.', 'an infrastructure plan is reviewed before applying production deletions.', 'giving a script unrestricted credentials because it runs unattended')
    ]),
    domain('Cloud Troubleshooting', 'Isolate identity, configuration, network, performance, capacity, dependency, deployment, and provider faults.', [
      concept('Cloud troubleshooting method', 'Cloud diagnosis defines scope, checks recent changes and service health, follows dependencies, gathers telemetry, tests hypotheses, and validates recovery.', 'one tenant fails while others work, narrowing attention to tenant configuration and identity.', 'restarting every component before preserving transient evidence'),
      concept('Identity and permission faults', 'Effective access can depend on user policy, role trust, resource policy, boundaries, conditions, organization controls, and explicit denies.', 'a denied action is traced through policy evaluation and audit logs.', 'adding administrator access without identifying the blocking control'),
      concept('Connectivity faults', 'Routes, gateways, DNS, security controls, load balancers, endpoints, MTU, and return paths must align across virtual and hybrid networks.', 'a private workload has a route but no permitted return path through policy.', 'assuming an open security group fixes a missing route'),
      concept('Deployment and dependency faults', 'Failed releases are analyzed through artifact version, configuration, secrets, health checks, dependencies, database state, quotas, and rollback evidence.', 'a canary fails because a rotated secret was not available to the new version.', 'rolling forward repeatedly without a known-good rollback point')
    ])
  ],
  scenarios: [
    { title: 'Public storage exposure', prompt: 'A posture alert reports that a bucket containing customer exports may be publicly readable.', steps: ['Validate without exposing data.', 'Contain public access.', 'Preserve audit evidence.', 'Assess data and access scope.', 'Prevent recurrence.'], model: 'Confirm policy and effective access through trusted tooling, block public access, preserve configuration and access logs, classify affected data, follow incident and notification procedures, rotate exposed links or credentials, and enforce preventive organization policy.' },
    { title: 'Regional application failure', prompt: 'One cloud region is unavailable and the recovery region has not been used in a year.', steps: ['Declare ownership and impact.', 'Check recovery dependencies and data freshness.', 'Follow tested runbook or controlled adaptation.', 'Shift traffic carefully.', 'Validate RPO, RTO, and user outcomes.'], model: 'Use the recovery plan, verify credentials, quotas, images, data replication, networking, DNS, certificates, and suppliers before traffic shift. Communicate risk and record deviations for a later exercise improvement.' },
    { title: 'Cloud bill doubles', prompt: 'Monthly cost doubled although customer traffic rose only ten percent.', steps: ['Allocate cost by service and tag.', 'Compare usage and price dimensions.', 'Find idle, oversized, or high-egress resources.', 'Protect reliability.', 'Assign and measure actions.'], model: 'Use billing exports and unit costs, identify unowned growth, egress, logs, snapshots, idle systems, scaling configuration, and pricing changes. Right-size and schedule safely, then monitor cost per business transaction and reliability.' },
    { title: 'New deployment returns errors', prompt: 'A canary deployment fails health checks while the old version remains healthy.', steps: ['Pause rollout.', 'Compare artifact and configuration.', 'Inspect logs, traces, secrets, network, and dependencies.', 'Rollback if thresholds require.', 'Correct and retest.'], model: 'Keep blast radius limited, preserve telemetry, compare immutable artifact, environment, feature flags, secrets, schema compatibility, policies, and quotas, then rollback or fix according to the release plan and validate with synthetic and user-facing checks.' }
  ], featuredScenario: 'Can you restore the service without losing the cloud evidence?',
  console: { label: 'CLOUD+ QUICK CHECK', command: 'route exists · connection still fails', lines: ['check security policy', 'check return path and DNS', 'inspect endpoint and service health'], explanationLabel: 'SHARED SYSTEM', explanation: 'Cloud connectivity requires aligned routes, policies, identities, endpoints, dependencies, and return traffic.' }
})
