import { glossary, modules as originalModules, quizQuestions, scenarios } from '../content'

const expandedSections = {
  foundations: [
    { title: 'What a data center server actually is', paragraphs: ['A server is a computer built to provide services reliably to other computers. It uses the same basic ideas as a desktop—processor, memory, storage, networking, power, and cooling—but enterprise servers are designed to run continuously, report their own health, and let technicians replace many parts without replacing the whole machine.', 'Picture a server as a small factory. The CPU is the workforce doing calculations, memory is the workbench holding active material, storage is the warehouse, network adapters are the loading docks, the motherboard is the road system, power supplies provide electricity, fans remove heat, and the BMC is the building supervisor watching everything even when production has stopped.'], terms: [['Chassis', 'The physical enclosure holding server parts.'], ['Motherboard', 'The main circuit board connecting components.'], ['FRU', 'A field-replaceable unit designed to be swapped during service.']], checkpoint: { question: 'Why can a server be powered off while its management interface still works?', answer: 'The BMC receives standby power separately from the main host components, so it can monitor and control the server while the host is off.' } },
    { title: 'The major components, one at a time', paragraphs: ['The CPU executes instructions. Modern server CPUs contain many cores and also control memory and PCIe communication. DIMMs provide fast temporary memory; their contents disappear when power is removed. Drives provide persistent storage. PCIe devices add capabilities such as networking, GPUs, or storage controllers. Every component depends on power, cooling, firmware, and a physical connection.', 'Redundancy improves availability. A server may contain two power supplies, several fans, multiple network ports, and mirrored drives so one failure does not immediately stop service. Redundant does not mean healthy: after one side fails, the server is operating with less protection and should be repaired deliberately.'], terms: [['CPU core', 'An independent execution unit inside a processor.'], ['DIMM', 'A removable memory module.'], ['PCIe', 'The high-speed connection used by expansion devices.'], ['Redundancy', 'Extra capacity or components that allow service to continue after a failure.']], checkpoint: { question: 'Which component keeps data after the server loses power: a DIMM or a drive?', answer: 'A drive. DIMM memory is volatile and loses its contents without power.' } },
    { title: 'From pressing power to running Linux', paragraphs: ['Booting happens in stages. Standby power starts the BMC. A power-on request enables the host. BIOS or UEFI performs the power-on self-test (POST), initializes the CPU, trains memory, and discovers PCIe devices. Firmware chooses a boot device. A bootloader such as GRUB loads the Linux kernel. Linux loads drivers, mounts storage, and starts services.', 'The last stage that succeeded is your most useful clue. No BMC access suggests management power or board trouble. BMC access but no POST suggests power, CPU, memory, board, or firmware initialization. POST success but no boot device points toward storage or configuration. A kernel that starts and then fails shifts attention toward drivers, filesystems, or services.'], steps: ['Confirm BMC access and power state.', 'Watch POST codes or the remote console.', 'Record the last successful initialization stage.', 'Check whether firmware sees the expected boot device.', 'Review Linux boot logs if the kernel starts.'], checkpoint: { question: 'A server completes POST but reports “no boot device.” Which fault domain becomes most likely?', answer: 'The boot configuration or storage path, because CPU, basic memory initialization, and much of the motherboard already completed POST.' } },
    { title: 'How hardware becomes visible in Linux', paragraphs: ['Firmware discovers hardware first, but Linux needs a driver to use it. Linux assigns names such as /dev/sda to a drive, enp65s0 to a network interface, and a bus:device.function address to a PCIe device. Inventory tools translate what the operating system sees into models, serials, capacities, and topology.', 'A device missing from an application may still be visible to Linux; a device missing from Linux may still appear in firmware or the BMC. Checking each layer prevents unnecessary replacement. Always map a logical name back to the physical bay, slot, or label before touching hardware.'], terms: [['Driver', 'Software that lets the operating system control hardware.'], ['Topology', 'How components and connections are arranged.'], ['Logical name', 'The identifier software uses for a physical device.']], checkpoint: { question: 'Why map /dev/sdb to a serial number before replacing a drive?', answer: 'Operating-system names can change between boots. Serial and bay mapping prevent removing the wrong drive.' } },
    { title: 'The beginner-safe diagnostic method', paragraphs: ['Good troubleshooting is controlled learning, not rapid part swapping. Start by stating exactly what is wrong, what is still working, when it began, and the business impact. Preserve volatile evidence before rebooting or clearing logs. Draw the fault domain—the smallest group of components that could explain the symptom—and list competing hypotheses.', 'Choose the safest test that best separates those hypotheses. Change one variable, record the result, and validate under the original conditions. This discipline protects production, makes your conclusion defensible, and gives a vendor evidence they can act on.'], steps: ['Protect people, data, and service.', 'Describe the symptom and impact precisely.', 'Preserve logs, versions, timestamps, and physical state.', 'Map the fault domain and rank hypotheses.', 'Perform one controlled test.', 'Validate recovery and document prevention.'], checkpoint: { question: 'Why is “reboot and see” a weak first diagnostic step?', answer: 'A reboot changes state and may erase evidence. It can restore service temporarily without identifying the cause.' } },
    { title: 'Worked example: server will not start', paragraphs: ['Suppose monitoring says a host is down and the front power button appears unresponsive. First confirm the asset and workload impact. Check BMC reachability. If the BMC is reachable, preserve its event log and sensors, then inspect host power state, PSU input, and recent events. If the BMC is unreachable, check both facility feeds, PDU outlets, cords, PSU LEDs, and standby-power indicators.', 'Do not replace the motherboard simply because the power button did nothing. Evidence may lead to a lost PDU feed, both cords on one failed circuit, mismatched PSUs, a front-panel connection, BMC failure, or board power fault. Each observation reduces the fault domain.'], checkpoint: { question: 'What can you conclude if the BMC is reachable?', answer: 'At least one standby-power path and part of the motherboard management subsystem are working.' } }
  ],
  power: [
    { title: 'Electricity without an engineering degree', paragraphs: ['Voltage is electrical pressure, current is flow, and power is the rate of energy use measured in watts. A power supply converts facility AC power into regulated DC voltages. The BMC watches voltage, current, power, and PSU status for unsafe values.', 'Technicians replace modules rather than repair energized power electronics. Understand the path—UPS, PDU, outlet, cord, PSU, power distribution, motherboard—and identify where healthy power stops. Follow site safety policy and never open a PSU.'], terms: [['AC', 'Alternating current supplied by the facility.'], ['DC', 'Direct current used by server electronics.'], ['PDU', 'Rack power distribution unit.'], ['Watt', 'A unit of power consumption.']], checkpoint: { question: 'What does a server PSU do?', answer: 'It converts facility AC power into stable DC voltages used by server components.' } },
    { title: 'Redundant feeds and PSUs', paragraphs: ['In a properly redundant design, PSU A and PSU B connect to independent power paths and share load. If one fails, the other keeps the system online but may now carry the entire load.', 'Check redundancy end to end. Two PSUs on the same PDU are not protected from PDU failure. A green LED does not prove correct load sharing. Use BMC readings, PDU data, labels, and a feed diagram.'], steps: ['Identify each PSU and cord.', 'Trace each cord to its PDU and upstream feed.', 'Check input, output, load, and capacity.', 'Restore redundancy.', 'Validate alarms and load sharing.'], checkpoint: { question: 'Why is one failed PSU still an incident if the server is online?', answer: 'Redundancy is lost, so a second failure can cause an outage and the remaining PSU may carry full load.' } },
    { title: 'Heat and airflow', paragraphs: ['Electricity becomes heat. Fans move cool air across components and exhaust warm air. Blocked airflow, missing blanks, dust, loose cables, failed fans, or a poor heatsink can cause throttling, errors, shutdowns, and shortened life.', 'Compare inlet, outlet, CPU, GPU, DIMM, and drive temperatures with workload and fan speed. One hot CPU suggests a local issue; many rising temperatures suggest room or airflow trouble. Trends are more useful than an isolated number.'], terms: [['Thermal throttling', 'Automatic performance reduction to limit heat.'], ['Inlet temperature', 'Air temperature entering the server.'], ['Hot aisle', 'The rack side receiving exhaust air.']], checkpoint: { question: 'Why can missing blanking panels cause overheating?', answer: 'Air can bypass intended component paths or recirculate instead of cooling hardware.' } },
    { title: 'ESD and safe hands-on work', paragraphs: ['Electrostatic discharge is a tiny spark that can damage electronics without being felt. Use approved grounding and ESD-safe packaging, hold boards by their edges, and avoid touching contacts.', 'Confirm the asset, drain workload, obtain authorization, label cables, and know whether a component is hot-swappable. Hot-swap means physically supported while powered; it does not mean every production policy permits immediate removal.'], terms: [['ESD', 'Electrostatic discharge.'], ['Hot-swap', 'Designed for insertion or removal while powered.'], ['Change control', 'Approval, communication, execution, and validation of a planned change.']], checkpoint: { question: 'Why use change control for a hot-swap PSU?', answer: 'The action can reduce redundancy, affect the wrong feed or asset, and create service risk.' } },
    { title: 'Power and thermal workflow', paragraphs: ['Begin with the precise symptom: total loss, one PSU alarm, shutdown, throttling, or high temperature. Build a timeline from monitoring, BMC, PDU, and workload data. Compare the affected sensor with healthy peers and trace shared dependencies.', 'After repair, confirm redundancy, capacity, sensor stability, fan behavior, alarms, and representative-load operation. A green LED alone is not proof.'], steps: ['Stabilize workload and preserve evidence.', 'Trace power and airflow paths.', 'Compare history and healthy peers.', 'Inspect the smallest fault domain.', 'Make one approved change.', 'Load-test and observe.'], checkpoint: { question: 'What proves a thermal repair worked?', answer: 'Temperatures remain stable under representative load, fans behave normally, alarms stay clear, and performance is restored.' } },
    { title: 'Worked example: intermittent throttling', paragraphs: ['A server slows every afternoon. Correlate CPU throttle events with CPU use, inlet temperature, fan speed, and room cooling. If all rack inlets rise together, the facility is likely involved. If one CPU runs hotter than its peer at similar load, inspect that socket’s cooling path during an approved outage.', 'State what would confirm each hypothesis before changing anything. This turns “server is slow” into a measurable thermal investigation.'], checkpoint: { question: 'Why compare both CPU sockets?', answer: 'They share much of the environment, so a large difference points toward a socket-specific heatsink, sensor, airflow, or workload issue.' } }
  ],
  memory: [
    { title: 'What memory does', paragraphs: ['RAM holds instructions and data a CPU needs immediately. It is fast but loses contents without power. Server memory is installed as DIMMs in labeled slots connected through channels to the CPU memory controller.', 'Population rules define slot order, supported sizes and speeds, and channel balance. A server may boot with a poor configuration but run slowly or produce errors. Use the exact service guide.'], terms: [['RAM', 'Fast volatile working memory.'], ['DIMM', 'A removable memory module.'], ['Channel', 'A data path between CPU and DIMMs.'], ['Memory controller', 'CPU logic that communicates with memory.']], checkpoint: { question: 'Why can a CPU cause memory errors?', answer: 'Modern CPUs contain the memory controller, so the controller, socket, or channel can fail.' } },
    { title: 'Bits, errors, and ECC', paragraphs: ['Computers store data as bits. Noise, aging cells, heat, radiation, or connection problems can change a bit. ECC memory adds check information so limited errors can be detected and corrected.', 'A corrected error was repaired before software used bad data, but a rising rate can predict failure. An uncorrected error exceeded correction capability and may cause a machine check, crash, or disabled DIMM.'], terms: [['Corrected error', 'Detected and repaired by ECC.'], ['Uncorrected error', 'Detected but not safely repairable.'], ['Machine check', 'A CPU-reported hardware error.']], checkpoint: { question: 'Does corrected mean ignore?', answer: 'No. Recurrence or increasing rate can predict failure and should be trended.' } },
    { title: 'Reading memory evidence', paragraphs: ['BMC logs may name a physical slot. Linux EDAC and machine-check logs may name a socket, channel, bank, or address. Vendor diagnostics may provide a predictive result. Align timestamps and map every logical label with the service manual.', 'Look beyond count: error velocity, repeated bit positions, temperature, workload, firmware, prior parts, and whether several DIMMs share a channel all change the hypothesis.'], steps: ['Export BMC logs.', 'Collect EDAC and MCE events.', 'Record firmware and inventory.', 'Map socket, channel, and slot.', 'Compare pattern over time.'], checkpoint: { question: 'Why do several affected DIMMs on one channel matter?', answer: 'They share a controller and path, making a CPU, socket, channel, or board fault more plausible.' } },
    { title: 'DIMM versus slot versus CPU', paragraphs: ['The reported DIMM is where an error was observed, not automatically the root cause. The DIMM, slot, board traces, CPU socket, memory controller, power, cooling, firmware, or population can look similar.', 'Use controlled substitution after preservation. If a fault follows a DIMM, suspect it. If it stays with the slot or channel, investigate the path. Change one variable and document serials and locations.'], checkpoint: { question: 'Why not swap several DIMMs at once?', answer: 'Multiple changes hide which action mattered and can introduce new seating or population problems.' } },
    { title: 'Safe isolation and validation', paragraphs: ['Drain and power down as required. Label original configuration. Move the suspect DIMM to a compatible known-good location or install a known-good DIMM in the suspect path. Run vendor memory diagnostics and representative workload.', 'A boot is not enough. Confirm capacity, population, clean POST and logs, diagnostic pass, workload stability, and no recurrence during an observation window.'], steps: ['Preserve evidence.', 'Check population rules.', 'Change one component or location.', 'Run diagnostics.', 'Recreate original load.', 'Observe and document.'], checkpoint: { question: 'What are good DIMM replacement pass criteria?', answer: 'Correct inventory, clean POST and diagnostics, stable representative load, and no recurrence.' } },
    { title: 'Worked example: rising ECC count', paragraphs: ['If DIMM A1 grows from two to 200 corrected errors in six hours, assess workload criticality and error velocity, preserve BMC and Linux evidence, map A1, inspect thermal history and firmware, then plan a controlled drain and isolation test.', 'Do not claim the DIMM is bad until evidence supports it. Communicate that service is currently running but reliability risk is increasing.'], checkpoint: { question: 'What makes a rising count more serious than one isolated error?', answer: 'The accelerating pattern suggests an active degradation mechanism rather than a rare transient event.' } }
  ],
  pcie: [
    { title: 'PCIe from the beginning', paragraphs: ['PCI Express connects CPUs to GPUs, network adapters, NVMe drives, and controllers. A connection uses lanes; more lanes carry more data. Each link negotiates a generation and width supported by endpoints and the path.', 'A Gen5 x16 card may intentionally run at x8 because of platform topology or bifurcation. Confirm design before diagnosing failure.'], terms: [['Lane', 'One transmit and receive signal path.'], ['Generation', 'A PCIe speed standard.'], ['Link width', 'Active lane count such as x8 or x16.'], ['Endpoint', 'A device at the end of a link.']], checkpoint: { question: 'Is x8 always wrong for an x16-capable card?', answer: 'No. The platform may intentionally provide x8, so compare with the design and a healthy peer.' } },
    { title: 'Topology and shared paths', paragraphs: ['A visible slot may connect through a cable, riser, retimer, switch, and CPU root port. Shared upstream components explain why several endpoints can fail together.', 'Use lspci -tv for the logical tree and the service guide for physical mapping. Record BDF, slot, serial, upstream bridge, CPU/NUMA node, power, and cooling.'], terms: [['BDF', 'Bus:device.function address.'], ['Riser', 'Board providing or repositioning slots.'], ['Retimer', 'Component restoring high-speed signals.'], ['Root port', 'CPU or chipset side of a link.']], checkpoint: { question: 'Why does a shared switch matter?', answer: 'One switch or upstream-link failure can affect several devices.' } },
    { title: 'Link training and AER', paragraphs: ['At initialization, endpoints agree on speed and width. Marginal cables, contacts, risers, power, retimers, or board traces can cause reduced width, retraining, or disappearance.', 'AER records corrected, uncorrected non-fatal, and fatal errors. Corrected events can warn of degradation; fatal events may remove the device. Map the BDF before touching hardware.'], checkpoint: { question: 'What can growing corrected AER errors indicate?', answer: 'Signal integrity may be degrading even though the link currently recovers.' } },
    { title: 'GPU-specific evidence', paragraphs: ['GPUs add high power, heat, firmware, drivers, and sometimes ECC memory. Collect vendor output, driver and firmware versions, temperature, power, clocks, ECC, Xid events, AER, topology, and workload timing.', 'An Xid is a clue, not an automatic replacement decision. Driver, PCIe, power, thermal, workload, and device faults can create different codes.'], steps: ['Record topology and identity.', 'Collect GPU and kernel logs.', 'Correlate power, temperature, and workload.', 'Compare healthy GPUs.', 'Reproduce safely.'], checkpoint: { question: 'Why does workload timing matter?', answer: 'It reveals whether power, heat, memory use, or a specific operation triggers failure and defines validation.' } },
    { title: 'Isolation and validation', paragraphs: ['Confirm configuration and firmware, inspect supported connections, then change one element: device, cable, riser, slot, or upstream path. If failure follows the device, suspect it; if it stays with the path, investigate shared infrastructure.', 'Validate expected device count, link state, topology, clean logs, sensors, and a representative full-system workload long enough to cover the original trigger.'], checkpoint: { question: 'Why test all GPUs together?', answer: 'Full load exercises shared power, cooling, and PCIe infrastructure that one-device testing misses.' } },
    { title: 'Worked example: disappearing GPU', paragraphs: ['For a GPU that disappears under load, correlate Xid, AER, power, temperature, and kernel events. Map cables, risers, switches, and PSUs shared with that GPU. Compare peers.', 'Use controlled load and one-at-a-time substitution. Define success before service: stable full load, correct link, clean logs, and no disappearance for the required observation period.'], checkpoint: { question: 'What does failure staying with a slot after swapping GPUs suggest?', answer: 'The slot, riser, cable, upstream link, power, board, or configuration is more likely than the GPU.' } }
  ],
  storage: [
    { title: 'How storage is organized', paragraphs: ['Storage keeps data without power. SATA and SAS drives often connect through a controller and backplane; NVMe drives use PCIe. Linux may see a physical device or one virtual disk created by a RAID controller.', 'Separate the logical volume from physical drive, bay, cable, backplane, controller, power, and cooling. That complete path is the fault domain.'], terms: [['Block device', 'Storage presented as addressable blocks.'], ['Backplane', 'Board connecting drives.'], ['Controller', 'Hardware or software managing drives.'], ['Virtual disk', 'Logical storage made from drives.']], checkpoint: { question: 'Why might Linux not show each RAID drive?', answer: 'A hardware controller can hide physical members and present one virtual disk.' } },
    { title: 'RAID and data risk', paragraphs: ['RAID 1 mirrors, RAID 5 and 6 use parity, and RAID 10 mirrors and stripes. RAID improves availability or performance but is not a backup because deletion, corruption, and shared failure remain possible.', 'A degraded array has lost redundancy. Rebuild stresses remaining drives. Verify RAID level, failed members, spares, rebuild state, backups, workload, serial, and bay before action.'], checkpoint: { question: 'Why can pulling the wrong drive destroy a degraded array?', answer: 'The remaining members may all be required to reconstruct data; removing another can make it unrecoverable.' } },
    { title: 'SMART, NVMe, and controller evidence', paragraphs: ['Health logs expose media errors, reallocated or pending sectors, interface CRC, timeouts, temperature, spare capacity, wear, and critical warnings. “PASSED” only means a threshold has not been crossed.', 'Interface errors may implicate cable or backplane. Several simultaneous dropouts suggest a shared controller, expander, power, firmware, or thermal path. Correlate exact timestamps.'], terms: [['Media error', 'Failure reading or writing the medium.'], ['CRC error', 'Communication data-integrity failure.'], ['Wear', 'Consumption of flash program/erase life.']], checkpoint: { question: 'What do simultaneous drive dropouts suggest?', answer: 'A shared path or environmental dependency rather than independent drive failures.' } },
    { title: 'Protect data before hardware', paragraphs: ['Confirm backups, restore confidence, array state, replication, workload risk, maintenance approval, and online-removal support. Use locate LEDs only after verifying mapping.', 'Cross-check controller identifier, drive serial, and physical bay. Photograph initial state. A stale label is not authoritative.'], steps: ['Preserve logs.', 'Confirm array and backups.', 'Map device to serial and bay.', 'Assess rebuild risk.', 'Perform one approved action.', 'Monitor data and rebuild.'], checkpoint: { question: 'Which identifiers should agree before pulling a drive?', answer: 'Logical/controller ID, serial number, and physical bay or locate indicator.' } },
    { title: 'Diagnose the whole path', paragraphs: ['One drive with media errors suggests the drive. Repeated resets and CRC errors suggest the path. Many drives disappearing suggest a shared dependency. Compare controller, kernel, enclosure, BMC, and application logs.', 'A new drive cannot fix a failed backplane. Fault-domain reasoning prevents repeat RMAs and repeated risky rebuilds.'], checkpoint: { question: 'A new drive has the same errors in the same bay. What now?', answer: 'The bay, backplane, cable, controller, power, or firmware becomes more likely.' } },
    { title: 'Rebuild and validation', paragraphs: ['Verify replacement identity, firmware, array membership, rebuild progress, controller health, performance, temperature, and error logs. Do not close because rebuild merely started.', 'After completion, confirm optimal state, integrity checks, monitoring, workload, and an observation window. Update serial and inventory records.'], checkpoint: { question: 'When is a storage RMA complete?', answer: 'After rebuild and integrity validation, healthy workload and monitoring, updated records, and failed-part return.' } }
  ],
  firmware: [
    { title: 'Firmware below the operating system', paragraphs: ['Firmware is software stored inside hardware. BIOS/UEFI initializes the platform, the BMC has management firmware, and controllers, drives, NICs, GPUs, PSUs, and retimers may each have firmware.', 'Compatibility is a system property. One update can require matching BMC, BIOS, driver, or controller versions. Use supported bundles and dependency order.'], terms: [['Firmware', 'Software controlling a hardware device.'], ['BIOS/UEFI', 'Platform initialization firmware.'], ['BMC', 'Independent management controller.']], checkpoint: { question: 'Why update versions together?', answer: 'Components and drivers rely on compatible interfaces; unsupported combinations can cause instability.' } },
    { title: 'Out-of-band management', paragraphs: ['iDRAC, iLO, IPMI, and Redfish expose sensors, logs, inventory, power, remote console, virtual media, and firmware without relying on Linux. This is crucial when the host is down.', 'The BMC is privileged. Restrict access, prefer secure interfaces, audit actions, and avoid unnecessary power operations. Correlate its evidence with other sources.'], checkpoint: { question: 'Why is the BMC out-of-band?', answer: 'It uses a management path independent of the host OS and production data path.' } },
    { title: 'System Event Log', paragraphs: ['SEL records temperature, voltage, ECC, PSU, reset, and other hardware events. It has limited space, may wrap, and its clock may differ from Linux.', 'Export detailed logs before clearing. Record BMC time and offset, align with monitoring and kernel events, and distinguish old history from current recurrence.'], steps: ['Export SEL and lifecycle logs.', 'Record BMC clock and firmware.', 'Normalize timestamps.', 'Correlate other sources.', 'Identify recurring sensors.'], checkpoint: { question: 'Why not clear SEL first?', answer: 'It destroys volatile evidence needed for timeline and recurrence analysis.' } },
    { title: 'Planning a safe update', paragraphs: ['Update because release notes, an advisory, vendor direction, or testing connects a version to the issue—not merely because newer exists. Verify exact model and revision.', 'Plan stable redundant power, drain, maintenance, settings backup, dependencies, reboots, rollback or recovery, and physical access. Some updates cannot be reversed.'], steps: ['Capture versions and settings.', 'Read release notes and known issues.', 'Verify compatibility and order.', 'Prepare recovery.', 'Apply in an approved window.', 'Validate inventory and symptom.'], checkpoint: { question: 'Why is “update latest” insufficient?', answer: 'It lacks symptom evidence, compatibility analysis, recovery planning, and validation.' } },
    { title: 'Failure and recovery', paragraphs: ['A failed update may leave a component unavailable, roll back, or require a recovery bank, jumper, image, or replacement. Do not interrupt an update because progress pauses.', 'Know expected duration and recovery indicators before starting. If failure occurs, preserve messages and follow the exact vendor procedure.'], checkpoint: { question: 'Why use redundant power during updates?', answer: 'Power loss while writing firmware can corrupt it and prevent hardware initialization.' } },
    { title: 'Post-update validation', paragraphs: ['Confirm targeted versions, settings, inventory, boot path, sensors, logs, and management access. Run diagnostics and representative workload, comparing the pre-change baseline.', 'A successful flash message is one check. The system must perform its production function reliably and the original symptom must be tested.'], checkpoint: { question: 'What is the final firmware validation?', answer: 'The original issue is resolved without new faults under representative operation.' } }
  ],
  linux: [
    { title: 'Why Linux matters', paragraphs: ['Linux is both the operating system and a hardware evidence source. The kernel discovers devices, loads drivers, reports machine checks, manages I/O, and records failures. You need confident navigation and log reading, not software-development expertise.', 'Commands should answer a question. Know whether a command only reads or changes state. Collect read-only evidence first.'], terms: [['Kernel', 'OS core managing hardware.'], ['Driver', 'Kernel component controlling a device.'], ['Journal', 'Structured system log.'], ['Root', 'Highly privileged account.']], checkpoint: { question: 'Why is the kernel log useful?', answer: 'The kernel directly observes device initialization, resets, machine checks, I/O, and link errors.' } },
    { title: 'Navigating safely', paragraphs: ['pwd shows location, ls lists files, cd changes directories, less reads, grep searches, and man explains commands. sudo grants permitted elevated execution. Redirection can overwrite files, so understand > and >>.', 'Capture output to an approved incident location with host identity and time. Do not send sensitive logs externally or run destructive copied commands without target verification.'], steps: ['Identify host and time.', 'Use an approved evidence path.', 'Run read-only inventory.', 'Bound logs by time and boot.', 'Preserve raw output.'], checkpoint: { question: 'Difference between > and >>?', answer: '> replaces a file; >> appends. The wrong one can destroy evidence.' } },
    { title: 'The evidence toolbox', paragraphs: ['journalctl -k reads kernel messages, dmesg reads the ring buffer, lspci inventories PCIe, dmidecode reads firmware tables, lsblk maps storage, smartctl and nvme-cli show drive health, and ipmitool reads BMC data.', 'Output is not a conclusion. Correlate identity and time, compare healthy peers, and understand which layer created each message.'], terms: [['Ring buffer', 'Limited in-memory kernel messages.'], ['DMI', 'Firmware inventory tables.'], ['Device node', 'A file-like interface to a device.']], checkpoint: { question: 'Why journalctl -k -b -1?', answer: 'It selects kernel messages from the previous boot where the failure may have occurred.' } },
    { title: 'Building a timeline', paragraphs: ['Define the incident window and normalize timestamps to UTC. Combine monitoring, tickets, BMC, Linux, application impact, changes, and physical actions. Align using shared anchor events.', 'An error after reset may be recovery, not cause. Record uncertainty rather than inventing exact order.'], steps: ['State impact start and recovery.', 'Export each source.', 'Record clock offsets.', 'Align shared events.', 'Separate indicators, actions, and recovery.'], checkpoint: { question: 'Why can the last error be misleading?', answer: 'It may be a consequence of an earlier fault or simply the last message written before logging stopped.' } },
    { title: 'Hypotheses and RCA', paragraphs: ['A hypothesis is testable. Write its predicted evidence: a bad DIMM should follow its serial; a bad slot should remain with the path. Choose the safest test separating explanations.', 'Root cause explains the mechanism. Symptoms are observations, contributing factors increase likelihood or impact, repair restores service, and prevention reduces recurrence.'], checkpoint: { question: 'Why is “replaced board” not root cause?', answer: 'It is an action, not the failed mechanism or evidence explaining why it worked.' } },
    { title: 'Writing and communicating', paragraphs: ['A useful RCA states impact, detection, timeline, cause, contributors, evidence, corrective action, and preventive actions with owners and dates. Avoid blame and unsupported certainty.', 'During incidents, communicate impact, owner, known evidence, next safe action, risk, and next update time. This prevents duplicate work and supports decisions.'], checkpoint: { question: 'What makes prevention strong?', answer: 'It is specific, owned, time-bound, measurable, and directly reduces the mechanism or detection gap.' } }
  ],
  rma: [
    { title: 'What an RMA is', paragraphs: ['RMA is the warranty repair or replacement process. It is not just ordering a part. The engineer validates failure, proves entitlement, coordinates the vendor, tracks logistics, qualifies replacement, returns the failed unit, and closes records.', 'Replacing without diagnosis increases no-fault-found returns, repeat failure, cost, and downtime. The process begins with evidence and ends with verified service.'], terms: [['Entitlement', 'Warranty or support coverage.'], ['NFF', 'No fault found on a returned part.'], ['Advance replacement', 'Replacement ships before failed part is received.']], checkpoint: { question: 'Why does RMA start before opening a case?', answer: 'Triage, evidence, isolation, identity, and entitlement are needed for an actionable claim.' } },
    { title: 'Validating the failed FRU', paragraphs: ['Map the fault domain, preserve evidence, check known issues and firmware, run supported diagnostics, and perform controlled substitution when safe. Record negative results too.', 'Confidence depends on risk. A clearly failed PSU may need little isolation; an intermittent board claim needs stronger evidence because retained components can mimic it.'], steps: ['Identify asset and impact.', 'Preserve logs and configuration.', 'Map topology.', 'Run vendor diagnostics.', 'Isolate component versus path.', 'Record failure signature.'], checkpoint: { question: 'What can high NFF mean?', answer: 'Weak diagnosis, intermittent test gaps, poor vendor tests, recovery during shipping, or wrong component isolation.' } },
    { title: 'Opening a useful vendor case', paragraphs: ['Provide model, serial, part, firmware, exact symptom, impact, timestamps, logs, diagnostics, topology, isolation, reproduction, and requested action. Use clear filenames and a concise timeline.', 'Answer vendor questions while protecting production and data. If a test is disruptive, explain constraints and offer equivalent evidence or an approved window.'], checkpoint: { question: 'Why is “server broken; send board” weak?', answer: 'It lacks identity, mechanism, evidence, isolation, impact, and a reason the board is the failed FRU.' } },
    { title: 'Logistics and custody', paragraphs: ['Track case, RMA, old and new serials, ship-to contact, tracking, SLA, deadlines, return label, packaging, and owner. Failed media may require sanitization or retention policy.', 'Inspect incoming parts for damage, model, revision, compatibility, and serial. Keep old and new parts clearly labeled.'], terms: [['Chain of custody', 'Documented possession and movement.'], ['DOA', 'Dead on arrival.'], ['Data retention', 'Policy controlling whether failed media can leave.']], checkpoint: { question: 'Why record both serials?', answer: 'For inventory, warranty history, chain of custody, repeat analysis, and installation proof.' } },
    { title: 'Replacement validation', paragraphs: ['Inspect and install under change control, verify inventory, run component diagnostics and representative workload, and check logs, sensors, performance, and the original signature.', 'A replacement can be wrong, damaged, incompatible, or fail early. Do not return the original or close the case before validation and rollback needs are satisfied.'], steps: ['Verify identity and condition.', 'Record serials.', 'Install correctly.', 'Run diagnostics.', 'Exercise original trigger.', 'Observe production.'], checkpoint: { question: 'When is boot insufficient?', answer: 'When the original fault required load, time, topology, temperature, or a specific operation.' } },
    { title: 'Metrics and fleet improvement', paragraphs: ['Track acknowledge, isolate, vendor response, arrival, restore, and close times. Measure failure, repeat RMA, NFF, recurrence, and reliability by component, model, lot, age, firmware, and environment.', 'Normalize by installed population or exposure time. Define windows and denominators. Use trends to improve playbooks, spares, procurement, baselines, vendor action, and training.'], terms: [['MTTR', 'Mean time to restore or repair.'], ['Repeat RMA rate', 'Share followed by another qualifying RMA.'], ['Failure rate', 'Failures relative to population or exposure.']], checkpoint: { question: 'What follows a repeat-RMA cluster?', answer: 'Validate data, find shared factors, mitigate risk, consolidate evidence, and drive corrective action.' } }
  ]
}

const modules = originalModules.map(module => ({ ...module, time: module.id === 'foundations' ? '75 min' : '60–75 min', sections: expandedSections[module.id] }))

export const infrastructureRole = {
  id: 'infrastructure-rma-hardware', category: 'Infrastructure & Data Centers', title: 'IT Infrastructure Engineer', subtitle: 'RMA & Hardware Diagnostics',
  level: 'Beginner to interview-ready', duration: '10–12 hours',
  description: 'Learn enterprise server hardware, safe diagnostics, Linux evidence, root cause analysis, and the complete RMA lifecycle from the ground up.',
  heroTitle: 'Build confidence from the rack up.',
  heroDescription: 'A complete, plain-language path from “What is a server?” to diagnosing production hardware and owning an OEM replacement.',
  modules, quizQuestions, glossary, scenarios,
  featuredScenario: 'Corrected ECC errors are rising on DIMM A1. What do you check first?',
  console: { command: '$ ipmitool sel list | grep -i ecc | tail -n 5', lines: ['08/26 09:21:33 | MEM | Corrected ECC | DIMM A1', '08/26 09:58:12 | MEM | Corrected ECC | DIMM A1', '08/26 10:32:47 | MEM | Corrected ECC | DIMM A1'], explanation: 'Corrected errors were repaired, but a rising count warrants investigation.' }
}
